=== xabertum/Ejercicios_JAVA/XML_TEST/public_html/actividad1.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT rrhh (NOTA?, persona*)>
<!ELEMENT NOTA ANY>
<!ELEMENT persona (nombre, apellidos, domicilios+, telefonos+, email, fechanacimiento, estudios*, curriculum*, aficiones*, idiomas*, observaciones?)>
<!ATTLIST persona
	dni CDATA #REQUIRED
>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT domicilios (domicilio+)>

<!ELEMENT telefonos (telefono+)>
<!ELEMENT telefono (#PCDATA)>
<!ATTLIST telefono
	tipo CDATA #REQUIRED
>

<!ELEMENT email (#PCDATA)>
<!ELEMENT fechanacimiento (#PCDATA)>
<!ELEMENT estudios (titulacion*)>
<!ELEMENT curriculum (puestodetrabajo+)>
<!ELEMENT aficiones (aficion+)>
<!ELEMENT idiomas (idioma+)>
<!ELEMENT observaciones (#PCDATA)>

<!ELEMENT domicilio (poblacion,CP,direccion)>
<!ATTLIST domicilio
	principal (si | no) #REQUIRED
>
<!ELEMENT CP (#PCDATA)>
<!ELEMENT poblacion (#PCDATA)>

<!ELEMENT direccion (tipovia, nombrevia,numero)>
<!ELEMENT tipovia (#PCDATA)>
<!ELEMENT nombrevia (#PCDATA)>
<!ELEMENT numero (#PCDATA)>


<!ELEMENT titulacion (titulo, añofin,centro)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT añofin (#PCDATA)>
<!ELEMENT centro (#PCDATA)>

<!ELEMENT puestodetrabajo (empresa, fechaalta, fechabaja, cargo, tareasrealizadas+)>
<!ELEMENT empresa (#PCDATA)>
<!ELEMENT fechaalta (#PCDATA)>
<!ELEMENT fechabaja (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT cargo (#PCDATA)>
<!ELEMENT tareasrealizadas (#PCDATA)>
<!ELEMENT aficion (#PCDATA)>

<!ELEMENT idioma (#PCDATA)>
<!ATTLIST idioma
	nivel (Alto | Medio | Bajo) #REQUIRED
>
<!ELEMENT observacions (#PCDATA)>

=== xabertum/Ejercicios_JAVA/XML_TEST/public_html/actividad1.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE rrhh SYSTEM "actividad1.dtd">
<rrhh>
    <NOTA>Correción/ejemplo de la actividad 1</NOTA>
    <persona dni="11.111.111">
        <nombre>Daniel</nombre>
        <apellidos>Garcia Lopez</apellidos>
        <domicilios>
            <domicilio principal="si">
                <poblacion>Vic</poblacion>
                <CP>08500</CP>
                <direccion>
                    <tipovia>Calle</tipovia>
                    <nombrevia>Verdaguer</nombrevia>
                    <numero>30</numero>
                </direccion>
            </domicilio>
            <domicilio principal="no">
                <poblacion>Barcelona</poblacion>
                <CP>08002</CP>
                <direccion>
                    <tipovia>Avenida</tipovia>
                    <nombrevia>Roma</nombrevia>
                    <numero>1, 3º, 2ª</numero>
                </direccion>
            </domicilio>
        </domicilios>
        <telefonos>
            <telefono tipo="movil">651447788</telefono>
            <telefono tipo="fijo">932223344</telefono>
        </telefonos>
        <email>dgl@uoc.edu</email>
        <fechanacimiento>4/7/1968</fechanacimiento>
        <estudios>
            <titulacion>
                <titulo>Ingeniero Informatica</titulo>
                <añofin>2001</añofin>
                <centro>UOC</centro>
            </titulacion>
            <titulacion>
                <titulo>Máster en educación y TIC</titulo>
                <añofin>2005</añofin>
                <centro>UOC</centro>
            </titulacion>
        </estudios>
        <curriculum>
            <puestodetrabajo>
                <empresa>hal informatica</empresa>
                <fechaalta>1/7/1986</fechaalta>
                <fechabaja>6/7/1992</fechabaja>
                <cargo>Programador</cargo>
                <tareasrealizadas>programación</tareasrealizadas>
            </puestodetrabajo>
            <puestodetrabajo>
                <empresa>Sistemas informaticos</empresa>
                <fechaalta>7/7/1992</fechaalta>
                <fechabaja>31/12/1997</fechabaja>
                <cargo>Analista programador</cargo>
                <tareasrealizadas>Analisis de requisitos</tareasrealizadas>
            </puestodetrabajo>
        </curriculum>
        <aficiones>
            <aficion>musica</aficion>
            <aficion>fotografia</aficion>
            <aficion>viajar</aficion>
        </aficiones>
        <idiomas>
            <idioma nivel="Alto">Ingles</idioma>
            <idioma nivel="Medio">Frances</idioma>
        </idiomas>
        <observaciones>Disminución física del 34%</observaciones>
    </persona>

    <persona dni="22.222.222">
        <nombre>Ricardo</nombre>
        <apellidos>Sanchez Ventura</apellidos>
        <domicilios>
            <domicilio principal="si">
                <poblacion>Cartagena</poblacion>
                <CP>30205</CP>
                <direccion>
                    <tipovia>Calle</tipovia>
                    <nombrevia>Sebastian de los Reyes</nombrevia>
                    <numero>15</numero>
                </direccion>
            </domicilio>
        </domicilios>
        <telefonos>
            <telefono tipo="movil">651112233</telefono>
            <telefono tipo="fijo">912223344</telefono>
        </telefonos>
        <email>rsv@hotmail.com</email>
        <fechanacimiento>1/1/1969</fechanacimiento>
        <estudios>
            <titulacion>
                <titulo>Ingeniero técnico Informatica</titulo>
                <añofin>2005</añofin>
                <centro>UPC</centro>
            </titulacion>
        </estudios>
        <curriculum>
            <puestodetrabajo>
                <empresa>BIT,S.A.</empresa>
                <fechaalta>1/10/1998</fechaalta>
                <fechabaja>30/6/2000</fechabaja>
                <cargo>Profesor</cargo>
                <tareasrealizadas>profesor visual basic</tareasrealizadas>
            </puestodetrabajo>
        </curriculum>
        <aficiones>
            <aficion>baile de salon</aficion>
        </aficiones>
        <idiomas>
            <idioma nivel="Medio">Ingles</idioma>
        </idiomas>
    </persona>
</rrhh>
