=== xabertum/Ejercicios_JAVA/XML_TEST/public_html/Departamento_RHH.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/Departamento_RHH.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE departamento_RRHH SYSTEM "Departamento_RHH.dtd">

    <departamento_RRHH>
    ...
    </departamento_RRHH>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT departamento_RRHH (persona)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT persona (datos_basicos|domicilios)*>
<!ATTLIST persona
    num_ref CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT datos_basicos (DNI|nombre|apellidos|fecha_nacimiento)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT DNI (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nombre (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT apellidos (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT fecha_nacimiento (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT domicilios (domicilio)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT domicilio (poblacion|cp|direccion)*>
<!ATTLIST domicilio
    principial CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT poblacion (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT cp (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT direccion (tipo|nombre_direccion|numero|puerta)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT tipo (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT nombre_direccion (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT numero (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT puerta (#PCDATA)>

=== xabertum/Ejercicios_JAVA/XML_TEST/public_html/departamento_RHH.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE departamento_RRHH SYSTEM "Departamento_RHH.dtd">
<departamento_RRHH>

    <persona num_ref="0025">
        <datos_basicos>
            <DNI>05920640A</DNI>
            <nombre>Javier</nombre>
            <apellidos>Delgado Mohatar</apellidos>
            <fecha_nacimiento>17-12-1982</fecha_nacimiento>
        </datos_basicos>

        <domicilios>
            <domicilio principial = "si">
                <poblacion>Puertollano</poblacion>
                <cp>13500</cp>
                <direccion>
                    <tipo>calle</tipo>
                    <nombre_direccion>maria de zayas</nombre_direccion>
                    <numero>1</numero>
                    <puerta></puerta>
                </direccion>
            </domicilio>

            <domicilio principial = "no">
                <poblacion>Puertollano</poblacion>
                <cp>13500</cp>
                <direccion>
                    <tipo>calle</tipo>
                    <nombre_direccion>daimiel</nombre_direccion>
                    <numero>6</numero>
                    <puerta></puerta>
                </direccion>
            </domicilio>
        </domicilios>
    </persona>

    <persona num_ref="0015">
        <datos_basicos>
            <DNI>05936648A</DNI>
            <nombre>Oscar</nombre>
            <apellidos>Perico Perez</apellidos>
            <fecha_nacimiento>17-12-1982</fecha_nacimiento>
        </datos_basicos>

        <domicilios>
            <domicilio principial = "si">
                <poblacion>Puertollano</poblacion>
                <cp>13500</cp>
                <direccion>
                    <tipo>calle</tipo>
                    <nombre_direccion>Maria de zayas</nombre_direccion>
                    <numero>1</numero>
                    <puerta>3</puerta>
                </direccion>
            </domicilio>

            <domicilio principial = "no">
                <poblacion>Puertollano</poblacion>
                <cp>13500</cp>
                <direccion>
                    <tipo>calle</tipo>
                    <nombre_direccion>daimiel</nombre_direccion>
                    <numero>6</numero>
                    <puerta></puerta>
                </direccion>
            </domicilio>
        </domicilios>
    </persona>

</departamento_RRHH>
